### ISSUE TITLE
How to formula 3D FFT for (x,y,t) in python

### ISSUE THREAD

**Issue by Canningz** [ZhangAoCanada/RADDet#11]
Hello ZhangAo, I'm not very familiar with signal processing, Can you tell me how you did  3D Fourier transform for (x,y,t) in Python? I didn't see related code in the repository

**Comment by ZhangAoCanada** [comment]
Hi, for the FFT part, I didn't uploaded it because it was developed during my internship at Sensor Cortek. I currently don't have their permission for open-sourcing the related code.
