### ISSUE TITLE
question about the the stero images annotation

### ISSUE THREAD

**Issue by malareeqi** [ZhangAoCanada/RADDet#14]
Hello ,thank you for your great work .
I want to do some tasks with the stereo images but when I have used the annotations provided with dataset, they weren't fit on the stereo images.
so please can you help me to get the stereo images annotations?Thank you so much.?

**Comment by ZhangAoCanada** [comment]
Hi,

You're right, there is no ground-truth annotation for the stereo images. 
During making this dataset, all the stereo annotations were not saved because my SSD has limited space. So, I don't have the backup for the stereo ground-truth...

**Comment by malareeqi** [comment]
okay got it,thank you so much
