### ISSUE TITLE
How to convert nuscenes radar point cloud to Range-Azimuth-Doppler format like in your paper ? 

### ISSUE THREAD

**Issue by 304886938** [ZhangAoCanada/RADDet#16]
Hello, your work is very meaningful!
Forgive me for my ignorance,
I want to know how to convert nuscenes radar point cloud to Range-Azimuth-Doppler format like in your paper.
Looking forward to your reply!

**Comment by ZhangAoCanada** [comment]
Hi, 

It is kinda hard to convert point cloud to RAD matrices, as the point cloud is generated from RAD matrices by sparse interpretation. And the process is from 3D to 2D. 

Therefore, to get RAD matrices, you probably have to capture the raw data from your radar. Then, use the basic process (FFT) on the raw data to acquire RAD matrices.

**Comment by 304886938** [comment]
Thank you for your answer!
