### ISSUE TITLE
How to do FFT on ADC data?

### ISSUE THREAD

**Issue by bodhiyang** [ZhangAoCanada/RADDet#20]
Hello,
What a fabulous job! I noticed that you have shared raw ADC data, which is the matrix with the shape of (256, 64, 4, 2). However, your literature (RADDet) mentioned that ADC data is a shape of (256, 8, 64). It seems that you have already performed the permutation on that. I was wondering how to do FFT on the range, azimuth, and doppler dimensions. i.e. the processing from raw ADC to RAD.
Thanks a lot!

**Comment by ZhangAoCanada** [comment]
Hi, thanks for your interests.

For the FFT part, it is relatively simple. Once you get the raw ADC data (sized (256, 64, 4, 2)), reshape them to (256, 64, 8). Then, you can perform FFT on dimension 256, 64, and 8 sequentially to achieve RAD. You can also permute the tensor if you want, e.g. reshape the tensor to (256, 8, 64) before FFTs. There's basically no difference between them.

I was trying to public the pre-processing part, but the copyright belongs to SensorCortek Inc. Therefore, instead, I public the raw ADC data to everyone for research purpose.

Ao
