### ISSUE TITLE
Radar Parameters

### ISSUE THREAD

**Issue by Mirage1089** [ZhangAoCanada/RADDet#24]
Hi,

I need to clarify some of the radar parameters. You have stated in the doc that,

```
"designed_frequency":			76.8 Hz,
"config_frequency":			77 Hz,
```
Is designed_frequency = Bandwidth?
config_frequency = career frequency?
Why both the frequencies are in Hz?
 
Thank you.

**Comment by ZhangAoCanada** [comment]
Hi,

`designed_frequency` is the frequency we got from a TI mmwave technician, and we used this for radar processing.
`config_frequency` is the frequency we used to config radar. Though we input 77Hz, the actual frequency of the radar is 76.8 Hz. That is the difference.

Thanks
