### ISSUE TITLE
Projection Matrix

### ISSUE THREAD

**Issue by BaiLiping** [ZhangAoCanada/RADDet#3]
Hi Ao, Congrats on your work. Pretty sure it is gonna be a high impact one. One question, in your paper: "Random locations were set for the calibration target with distances to the sensors ranging from5mto50m. The projection matrix from the 3D stereo frame to the bird-eye-view radar frame is computed with least square optimization. Raw ADC data captured from the radar have a shape of(256,8,64)." would is be possible for me to find this matrix? I looked into your paper and code, seems that it is no where to be found. Thanks

**Comment by ZhangAoCanada** [comment]
Hi, Liping

Thanks for your kind words.

I made some changes according to your request, see https://github.com/ZhangAoCanada/RADDet/commit/d680b033a346fb2d6907cfde6509246696848e64.

For details, I uploaded an additional folder sensors_para to all the existing dataset cloud drives for the stereo depth estimation and sensors registration. 
**Note**: The registration matrix you asked for is inside the subdirectory `registration_matrix`.
**Note**: Inside the subdirectory `stereo_para`, `left_maps.npy` and `right_maps.npy` are derived from `cv2.initUndistortRectifyMap(...)`; all other matrices are derived from `cv2.stereoRectify(...)`.

The registration/annotation repository is developed with Sensor Cortek Inc. So I didn't open-source that repo.

Let me know if there is anything else.
