### ISSUE TITLE
Mean average precision computation

### ISSUE THREAD

**Issue by colindecourt** [ZhangAoCanada/RADDet#7]
Hi, 
While evaluating your model and reading the code, I noticed something weird in the computation of the mean average precision.
```
...
for class_i in all_gt_classes:
        ### NOTE: get the prediction per class and sort it ###
        pred_class = predictions[predictions[..., 7] == class_i]
        pred_class = pred_class[np.argsort(pred_class[..., 6])[::-1]]
        ### NOTE: get the ground truth per class ###
        gt_class = gts[gts[..., 6] == class_i]
        tp, fp = getTruePositive(pred_class, gt_class, input_size, \
                                iou_threshold=tp_iou_threshold, mode=mode)
...
```
When iterating over all_gt_classes only the detection having the same class as the ground truth are counted as false positive or true positive. Therefore, it doesn't count the detection that has a different label than one of those in a given image. As an example, in a spectrum where the ground truths are: 2 cars and 1 pedestrian and the predictions: 2 cars and 1 bicycle, using your code detection with the class bicycle don't seem to be counted as a false positive. Is there any reason for this choice? Am I wrong in my analysis?
Thanks for your response.

**Comment by ZhangAoCanada** [comment]
Hi, the reference of mAP code in this repo is from [Cartucho/mAP](https://github.com/Cartucho/mAP.git). The evaluation process is carried out as: first output the predictions from the model on the entire test set, then perform class-wise mAP calculation. The average AP of all the classes is computed as the average of all class-wise AP. So, the AP in the paper is not calculated under 1 or few input samples. 

If you prefer to compute AP using limited input samples, you could change `all_gt_classes` to all the classes shown in `config.json`. Be careful about the situation where 0/0 appears.

Hope this could help.
