### ISSUE TITLE
can't find radar processing codes about (RA,RD)

### ISSUE THREAD

**Issue by xuzekai1997** [ZhangAoCanada/RADDet#8]
Hi.
I am reading your codes in recent days.But I didn't find any codes about radar processing,such as  getting RA map or RD map.
And also, for files in RAD directory like 000090.npy ,I load it to python,But I have no idea of the data format of it. 
So ,could you give me some advice about these problems?
Thank you very much and  I am waiting for your reply.

**Comment by ZhangAoCanada** [comment]
Hi,
The explanation you are looking for is probably in `visualize_testdata.py`, in the project root directory. It is for visualizing the test data with input on RA RD Catesian, and gt as bounding boxes.
