### ISSUE TITLE
How to get the RAD from ADC data

### ISSUE THREAD

**Issue by Janpeterson2046** [ZhangAoCanada/RADDet#9]
Hi! 

regarding the processing of ADC data to get the RAD, i tried to zero padd the ADC in the Angular dimension (as described in your paper: ) ) and directly perform 3D FFT without the windows on the zero padded ADC data, somehow i can not get the same RAD as you got, and i am wondering the raw ADC data would be normalised before applying the 3D FFT? It would be great if you could provide more details or codes regarding this part! Thanks a lot in advanced : ) !

bests,
Jan

**Comment by xuzekai1997** [comment]
Hi.
I have the same problem about getting RAD from ADC data.
So,could you give some advice about this part.
Thank you very much!
Bests wishes.

**Comment by ZhangAoCanada** [comment]
Hi, 

This part was done during my internship at Sensor Cortek, so they have the copyright of the code.
I have emailed them a few days ago, and still waiting for their reply on whether I can have the permission to open-source it.

Thanks,

**Comment by Janpeterson2046** [comment]
thank for all the informations!
